export const substitutions: Record<string, string> = {
  "Alpha": "Α",
  "Beta": "Β",
  "Gamma": "Γ",
  "Delta": "Δ",
  "Epsilon": "Ε",
  "Zeta": "Ζ",
  "Eta": "Η",
  "Theta": "Θ",
  "Iota": "I",
  "Kappa": "Κ",
  "Lambda": "Λ",
  "Mu": "Μ",
  "Nu": "Ν",
  "Xi": "Ξ",
  "Omicron": "Ο",
  "Pi": "Π",
  "Rho": "Ρ",
  "Sigma": "Σ",
  "Tau": "Τ",
  "Upsilon": "Υ",
  "Phi": "Φ",
  "Chi": "Χ",
  "Psi": "Ψ",
  "Omega": "Ω",

  "alpha": "α",
  "beta": "β",
  "gamma": "γ",
  "delta": "δ",
  "epsilon": "ϵ",
  "zeta": "ζ",
  "eta": "η",
  "theta": "θ",
  "iota": "ι",
  "kappa": "κ",
  "lambda": "λ",
  "mu": "μ",
  "nu": "ν",
  "xi": "ξ",
  "omicron": "ο",
  "pi": "π",
  "rho": "ρ",
  "sigma": "σ",
  "tau": "τ",
  "upsilon": "υ",
  "phi": "φ",
  "chi": "χ",
  "psi": "ψ",
  "omega": "ω",

  "varepsilon": "ε",
  "varnothing": "∅",
  "varkappa": "ϰ",
  "varphi": "ɸ",
  "varpi": "ϖ",
  "varrho": "ϱ",
  "varsigma": "ς",
  "vartheta": "ϑ",

  "_0": "₀",
  "_1": "₁",
  "_2": "₂",
  "_3": "₃",
  "_4": "₄",
  "_5": "₅",
  "_6": "₆",
  "_7": "₇",
  "_8": "₈",
  "_9": "₉",
  "^0": "⁰",
  "^1": "¹",
  "^2": "²",
  "^3": "³",
  "^4": "⁴",
  "^5": "⁵",
  "^6": "⁶",
  "^7": "⁷",
  "^8": "⁸",
  "^9": "⁹",

  "_+": "₊",
  "_-": "₋",
  "^+": "⁺",
  "^-": "⁻",

  _a: "ₐ",
  _e: "ₑ",
  _h: "ₕ",
  _i: "ᵢ",
  _j: "ⱼ",
  _k: "ₖ",
  _l: "ₗ",
  _m: "ₘ",
  _n: "ₙ",
  _o: "ₒ",
  _p: "ₚ",
  _r: "ᵣ",
  _s: "ₛ",
  _t: "ₜ",
  _u: "ᵤ",
  _v: "ᵥ",
  _x: "ₓ",
  "^a": "ᵃ",
  "^b": "ᵇ",
  "^c": "ᶜ",
  "^d": "ᵈ",
  "^e": "ᵉ",
  "^f": "ᶠ",
  "^g": "ᵍ",
  "^h": "ʰ",
  "^i": "^i",
  "^j": "ʲ",
  "^k": "ᵏ",
  "^l": "ˡ",
  "^m": "ᵐ",
  "^n": "ⁿ",
  "^o": "ᵒ",
  "^p": "ᵖ",
  "^r": "ʳ",
  "^s": "ˢ",
  "^t": "ᵗ",
  "^u": "ᵘ",
  "^v": "ᵛ",
  "^w": "ʷ",
  "^x": "ˣ",
  "^y": "ʸ",
  "^z": "ᶻ",
  "*": "⋅",
  "**": "∗",
  "***": "⋆",
  "//": "/",
  "\\\\": "\\",
  "xx": "×",
  "-:": "÷",
  "|><": "⋉",
  "><|": "⋊",
  "|><|": "⋈",
  "@": "∘",
  "o+": "⊕",
  "ox": "⊗",
  "o.": "⊙",
  "sum": "Σ",
  "prod": "Π",
  "lim": "**lim**",
  "^^": "∧",
  "^^^": "⋀",
  "vv": "∨",
  "vvv": "⋁",
  "nn": "∩",
  "nnn": "⋂",
  "uu": "∪",
  "uuu": "⋃",

  "sqrt": "√",
  "root": "√",
  "int": "∫",
  "oint": "∮",
  "del": "∂",
  "grad": "∇",
  "+-": "±",
  "O/": "∅",
  "oo": "∞",
  "aleph": "ℵ",

  ":.": "∴",
  ":'": "∵",
  "...": "⋯",
  "/_": "∠",
  "/_\\": "△",
  "diamond": "⋄",
  "square": "□",
  "|__": "⌊",
  "__|": "⌋",
  "|~": "⌈",
  "~|": "⌉",
  "CC": "ℂ",
  "NN": "ℕ",
  "QQ": "ℚ",
  "RR": "ℝ",
  "ZZ": "ℤ",

  "!=": "≠",
  "<=": "≤",
  ">=": "≥",
  "-<": "≺",
  "-<=": "⪯",
  ">-": "≻",
  ">-=": "⪰",
  "in": "∈",
  "!in": "∉",
  "sub": "⊂",
  "sup": "⊃",
  "sube": "⊆",
  "supe": "⊇",
  "-=": "≡",
  "~=": "≅",
  "~~": "≈",
  "prop": "∝",

  "and": "**and**",
  "or": "**or**",
  "not": "¬",
  "=>": "⇒",
  "if": "**if**",
  "<=>": "⇔",
  "AA": "∀",
  "EE": "∃",
  "_|_": "⊥",
  "TT": "⊤",
  "|--": "⊢",
  "|==": "⊨",

  "<<": "⟨",
  ">>": "⟩",

  "uarr": "↑",
  "uparrow": "↑",
  "darr": "↓",
  "downarrow": "↓",
  "rarr": "→",
  "rightarrow": "→",
  "->": "→",
  "to": "→",
  ">->": "↣",
  "->>": "↠",
  ">->>": "⤖",
  "|->": "↦",
  "mapsto": "↦",
  "larr": "←",
  "leftarrow": "←",
  "harr": "↔",
  "leftrightarrow": "↔",
  "rArr": "⇒",
  "Rightarrow": "⇒",
  "lArr": "⇐",
  "Leftarrow": "⇐",
  "hArr": "⇔",
  "Leftrightarrow": "⇔",

  " hat": "\u0302",
  " bar": "\u0305",
  " dot":"\u0305",
  " ul": "\u0332",
  " vec": "\u20D7",
  " tilde": "\u0303",
  " ddot": "\u0308",
  " cancel": "\u0338",
};

export const normalAlphabet = "qwertyuiop asdfghjkl zxcvbnm QWERTYUIOP ASDFGHJKL ZXCVBNM";
export const alphabets: Record<string, string[]> = {
  "fr": [..."𝔮𝔴𝔢𝔯𝔱𝔶𝔲𝔦𝔬𝔭 𝔞𝔰𝔡𝔣𝔤𝔥𝔧𝔨𝔩 𝔷𝔵𝔠𝔳𝔟𝔫𝔪 𝔔𝔚𝔈ℜ𝔗𝔜𝔘ℑ𝔒𝔓 𝔄𝔖𝔇𝔉𝔊ℌ𝔍𝔎𝔏 ℨ𝔛ℭ𝔙𝔅𝔑𝔐"],
}

export default function processMath(math: string): string {
  let rv = math;
  rv = applySubstitutions(rv);
  rv = applyAlphabets(rv);
  return rv;
}

function applySubstitutions(rv: string) {
  for(const subst in substitutions) {
    rv = rv.replaceAll(subst, substitutions[subst]);
  }
  return rv;
}

function applyAlphabets(rv: string): string {
  const regexBase = String.raw`"((?:[^"]|\\")*)"`;
  console.log("Applying alphabets", regexBase);
  for (const alphabet in alphabets) {
    const regex = new RegExp(alphabet + regexBase);
    console.log("Constructed regex:", regex);
    rv = applyAlphabet(rv, regex, alphabets[alphabet]);
  }
  return rv;

  function applyAlphabet(rv: string, regex: RegExp, alphabet: string[]): string {
    return rv.replace(regex, (_, ...groups) => {
      const [text] = groups;
      const rendered = [];
      for (const ch of text) {
        rendered.push(alphabet[normalAlphabet.indexOf(ch)] ?? ch);
      }
      return rendered.join("");
      //
    })
  }
}
